# Generated by Django 2.0 on 2017-12-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
