# Generated by Django 2.0 on 2017-12-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_practice', '0002_auto_20171217_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
